// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WilbertManagement.api.Data;

namespace WilbertManagement.api.Migrations
{
    [DbContext(typeof(WilbertManagementapiDBContext))]
    partial class WilbertManagementapiDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WilbertFSvcs.Model.Entities.FuneralHomeContact", b =>
                {
                    b.Property<int>("FuneralHomeContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ContactRole")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FuneralHomeId")
                        .HasColumnType("int");

                    b.Property<string>("Interests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("ShowPrices")
                        .HasColumnType("bit");

                    b.Property<string>("Spouse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuneralHomeContactId");

                    b.ToTable("FuneralHomeContact");
                });

            modelBuilder.Entity("WilbertFSvcs.Models.Misc.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int?>("FuneralHomeContactId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneType")
                        .HasColumnType("int");

                    b.HasKey("PhoneId");

                    b.HasIndex("FuneralHomeContactId");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("WilbertFSvcs.Models.Misc.Phone", b =>
                {
                    b.HasOne("WilbertFSvcs.Model.Entities.FuneralHomeContact", null)
                        .WithMany("PhNumbers")
                        .HasForeignKey("FuneralHomeContactId");
                });

            modelBuilder.Entity("WilbertFSvcs.Model.Entities.FuneralHomeContact", b =>
                {
                    b.Navigation("PhNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
